# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bloader < Formula
  desc ""
  homepage ""
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cresplanex/bloader/releases/download/v1.0.0/bloader_ 1.0.0_Darwin_x86_64.tar.gz"
      sha256 "04fa53e01dd5e1a9db565ac66f02a8962dfeff2f8550bf66b2c6db2a1ae1adaa"

      def install
        bin.install "bloader"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cresplanex/bloader/releases/download/v1.0.0/bloader_ 1.0.0_Darwin_arm64.tar.gz"
      sha256 "1a5edc5b39b0189c350c3be7716f25e24c4875289dd04acacd1046e93c602b94"

      def install
        bin.install "bloader"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cresplanex/bloader/releases/download/v1.0.0/bloader_ 1.0.0_Linux_x86_64.tar.gz"
        sha256 "be91fcaa1a2371b041e13029ae0f6e77e3215b7dcaa94a25ddf8fca327fd8754"

        def install
          bin.install "bloader"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cresplanex/bloader/releases/download/v1.0.0/bloader_ 1.0.0_Linux_arm64.tar.gz"
        sha256 "3d7b12995a48d6a07a07915beadac8bcec33fe54e961c8d4b789cd1e16aa201a"

        def install
          bin.install "bloader"
        end
      end
    end
  end
end
