# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bloader < Formula
  desc ""
  homepage ""
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cresplanex/bloader/releases/download/v1.0.0/bloader_ 1.0.0_Darwin_x86_64.tar.gz"
      sha256 "f5f768c59c318930bfd54629e4e206da40594820ad76e2335be02bda10172885"

      def install
        bin.install "bloader"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cresplanex/bloader/releases/download/v1.0.0/bloader_ 1.0.0_Darwin_arm64.tar.gz"
      sha256 "ba7c0cb459713bf2f7d9dd99ee524254e937f1014b1c2b72a41364513c1b5cf8"

      def install
        bin.install "bloader"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cresplanex/bloader/releases/download/v1.0.0/bloader_ 1.0.0_Linux_x86_64.tar.gz"
        sha256 "67244a9490a10a8d0a803e78333b836f46ce946fba5e1077ed0bb5cba6c8e2ec"

        def install
          bin.install "bloader"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cresplanex/bloader/releases/download/v1.0.0/bloader_ 1.0.0_Linux_arm64.tar.gz"
        sha256 "190d386600455d13ef326b8c083f474b0097d0476054693e88749a8231ef37c8"

        def install
          bin.install "bloader"
        end
      end
    end
  end
end
