# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bloader < Formula
  desc ""
  homepage ""
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cresplanex/bloader/releases/download/v1.0.0/bloader_ 1.0.0_Darwin_x86_64.tar.gz"
      sha256 "1a18329b456b5486057a45bc95841da80a12462ef29fab074a669525c5623cdd"

      def install
        bin.install "bloader"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cresplanex/bloader/releases/download/v1.0.0/bloader_ 1.0.0_Darwin_arm64.tar.gz"
      sha256 "330c89fca7232472b7f8cbb4c3378a85902ba72b70d21e4b238262d6db4ec8f0"

      def install
        bin.install "bloader"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cresplanex/bloader/releases/download/v1.0.0/bloader_ 1.0.0_Linux_x86_64.tar.gz"
        sha256 "d1957acc05db7dac847240a2e8b0590e19454b2a4909ce264984b85213fe2b8d"

        def install
          bin.install "bloader"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cresplanex/bloader/releases/download/v1.0.0/bloader_ 1.0.0_Linux_arm64.tar.gz"
        sha256 "1a919d85b50f73bac295c8af3c47d01ecb7f6769a5beb656d113dc749e7e79a8"

        def install
          bin.install "bloader"
        end
      end
    end
  end
end
